drive_cleanup:
	# Delete files that won't be needed. .exe, .jar etc..
	C:\Users\dasso\.virtualenvs\UsefulTools-KSc5YkS7\Scripts\python.exe delete_files.py 'D:'

	#C:\Users\dasso\.virtualenvs\UsefulTools-KSc5YkS7\Scripts\python.exe remove_dead_links.py 'D:'
	#C:\Users\dasso\.virtualenvs\UsefulTools-KSc5YkS7\Scripts\python.exe consolidate_files.py 'D:'
	#C:\Users\dasso\.virtualenvs\UsefulTools-KSc5YkS7\Scripts\python.exe DuplicateFiles.py
	#C:\Users\dasso\.virtualenvs\UsefulTools-KSc5YkS7\Scripts\python.exe clean_up_link_files.py 'D:'
